name: dart_mpesa
description: This library contains methods that make it easy to consume Mpesa Api.
version: 2.0.3
homepage: https://github.com/EddieKamau/dart_mpesa
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^0.13.3
  
dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  pedantic: ^1.10.0
  test: ^1.16.0
  mockito: ^5.0.12
