name: dart_mpesa
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  enum_object: ^0.0.2
  
dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  pedantic: ^1.10.0
  test: ^1.16.0
  mockito: ^5.0.12
